
    
aliases:
  - &root-yarn |
    yarn install --non-interactive --cache-folder ~/.cache/yarn

  - &root-restore-yarn-cache
    keys:
      - root-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # Fallback in case checksum fails
      - root-yarn-{{ .Branch }}-

  - &root-save-yarn-cache
    paths:
      - node_modules
      - ~/.cache/yarn
    key: root-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}

  - &filter-only-source
    branches:
      only:
        - source

  - &filter-ignore-master
    branches:
      ignore: master

  - &root-checkout
    path: ~/unmock.github.io

  - &root-build
    name: Run build
    command: yarn build


defaults: &defaults
  working_directory: ~/unmock.github.io/website
  docker:
    - image: circleci/node:8

version: 2
jobs:
  tests:
    <<: *defaults
    steps:
      - checkout: *root-checkout
      - run: *root-yarn
      - save_cache: *root-save-yarn-cache
      - run:
          name: "Run linter"
          command: "echo 'Skipping linter until theres something to lint';"
  deploy:
    <<: *defaults
    steps:
      - checkout: *root-checkout
      - run: *root-yarn
      - save_cache: *root-save-yarn-cache
      - run: *root-build
      - run:
          name: Configure GitHub Bot and deploy
          command: |
            if [[ $CIRCLE_PROJECT_USERNAME == "unmock" && -z $CI_PULL_REQUEST && -z $CIRCLE_PR_USERNAME ]]; then
              echo "Deploying website..."
              git config --global user.email $GITHUB_USERNAME@users.noreply.github.com
              git config --global user.name $GITHUB_USERNAME
              echo "machine github.com login $GITHUB_USERNAME password $GITHUB_TOKEN" > ~/.netrc
              GIT_USER=$GITHUB_USERNAME CURRENT_BRANCH=source USE_SSH=false yarn run publish-gh-pages
            else
              echo "Skipping deploy"
            fi
workflows:
  version: 2
  build-deploy:
    jobs:
      - tests:
          filters: *filter-ignore-master
      - deploy:
          requires:
           - tests
          filters: *filter-only-source
